/**
 * @fileoverview gRPC-Web generated client stub for count.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.1
// source: count.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.count = {};
proto.count.v1 = require('./count_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.count.v1.CountServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.count.v1.CountServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.count.v1.CountRequest,
 *   !proto.count.v1.CountResponse>}
 */
const methodDescriptor_CountService_Count = new grpc.web.MethodDescriptor(
  '/count.v1.CountService/Count',
  grpc.web.MethodType.UNARY,
  proto.count.v1.CountRequest,
  proto.count.v1.CountResponse,
  /**
   * @param {!proto.count.v1.CountRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.count.v1.CountResponse.deserializeBinary
);


/**
 * @param {!proto.count.v1.CountRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.count.v1.CountResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.count.v1.CountResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.count.v1.CountServiceClient.prototype.count =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/count.v1.CountService/Count',
      request,
      metadata || {},
      methodDescriptor_CountService_Count,
      callback);
};


/**
 * @param {!proto.count.v1.CountRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.count.v1.CountResponse>}
 *     Promise that resolves to the response
 */
proto.count.v1.CountServicePromiseClient.prototype.count =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/count.v1.CountService/Count',
      request,
      metadata || {},
      methodDescriptor_CountService_Count);
};


module.exports = proto.count.v1;

